name: Abimael Martell
permalink: /blog/:title.html
baseurl:
description: developer
url: http://abimaelmartell.com
meta_description: "Abimael Martell's personal website and blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15
author: 'Abimael Martell'
