name: Abimael Martell
permalink: /blog/:title.html
description: Software Developer
url: http://abimaelmartell.com
meta_description: "Abimael Martell's personal website and blog"
highlighter: rouge
author: 'Abimael Martell'

defaults:
  -
    scope:
      path: ""
    values:
      comments: true
